stages:
  - build
  - test
  - delivery


build-job:
  stage: build
  tags:
    - TestRunner
  script:
    - docker compose -f docker-compose-test.yml build

test-job:
  stage: test
  tags:
    - TestRunner
  script:
    - docker compose -f docker-compose-test.yml up --abort-on-container-exit
    - docker compose -f docker-compose-test.yml down

delivery-job:
  stage: delivery
  tags:
    - TestRunner
  only:
    - main
  script:
    - docker login gitlabhomevlad.ru:5050
    - docker build -t gitlabhomevlad.ru:5050/root/telegrambot .
    - docker push gitlabhomevlad.ru:5050/root/telegrambot
