stages:
  - test
  - delivery

test-job:
  stage: test
  tags:
    - TestRunner
  script:
    - docker compose -f docker/test/docker-compose.yml down
    - docker compose -f docker/test/docker-compose.yml build
    - docker compose -f docker/test/docker-compose.yml up --abort-on-container-exit

delivery_job:
  stage: delivery
  tags:
    - TestRunner
  only:
    - main
  script:
    - docker login gitlabhomevlad.ru:5050
    - docker build -t gitlabhomevlad.ru:5050/root/telegrambot .
    - docker push gitlabhomevlad.ru:5050/root/telegrambot
