stages:
  - test
  - delivery

test-job:
  stage: test
  tags:
    - TestRunner
  script:
    - docker compose -f docker-compose-test.yml down
    - docker compose -f docker-compose-test.yml build
    - docker compose -f docker-compose-test.yml up
    - docker compose -f docker-compose-test.yml down

delivery_job:
  stage: delivery
  tags:
    - TestRunner
  only:
    - main
  script:
    - docker login gitlabhomevlad.ru:5050
    - docker build -t gitlabhomevlad.ru:5050/root/telegrambot .
    - docker push gitlabhomevlad.ru:5050/root/telegrambot
